//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartanClash.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class test_clashdbEntities : DbContext
    {
        public test_clashdbEntities()
            : base("name=test_clashdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<mv_Blue_Results> mv_Blue_Results { get; set; }
        public DbSet<mv_Red_Results> mv_Red_Results { get; set; }
        public DbSet<t_clanbattleparticipants> t_clanbattleparticipants { get; set; }
        public DbSet<t_results> t_results { get; set; }
        public DbSet<t_spartans> t_spartans { get; set; }
        public DbSet<t_clanbattles> t_clanbattles { get; set; }
    }
}
