//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartanClash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_clanbattleparticipants
    {
        public string MatchId { get; set; }
        public Nullable<int> Team1_Rank { get; set; }
        public Nullable<int> Team2_Rank { get; set; }
        public Nullable<long> Team1_Score { get; set; }
        public Nullable<long> Team2_Score { get; set; }
        public string Team1_Company1 { get; set; }
        public string Team1_Company2 { get; set; }
        public string Team2_Company1 { get; set; }
        public string Team2_Company2 { get; set; }
        public string Team1_Player_1 { get; set; }
        public string Team1_Player_2 { get; set; }
        public string Team1_Player_3 { get; set; }
        public string Team1_Player_4 { get; set; }
        public string Team1_Player_5 { get; set; }
        public string Team1_Player_6 { get; set; }
        public string Team1_Player_7 { get; set; }
        public string Team1_Player_8 { get; set; }
        public string Team1_Player_9 { get; set; }
        public string Team1_Player_10 { get; set; }
        public string Team1_Player_11 { get; set; }
        public string Team1_Player_12 { get; set; }
        public string Team2_Player_1 { get; set; }
        public string Team2_Player_2 { get; set; }
        public string Team2_Player_3 { get; set; }
        public string Team2_Player_4 { get; set; }
        public string Team2_Player_5 { get; set; }
        public string Team2_Player_6 { get; set; }
        public string Team2_Player_7 { get; set; }
        public string Team2_Player_8 { get; set; }
        public string Team2_Player_9 { get; set; }
        public string Team2_Player_10 { get; set; }
        public string Team2_Player_11 { get; set; }
        public string Team2_Player_12 { get; set; }
    }
}
