//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartanClash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_clashdevset
    {
        public string MatchId { get; set; }
        public Nullable<int> GameMode { get; set; }
        public string HopperId { get; set; }
        public string MapId { get; set; }
        public Nullable<int> MapVariant_ResourceType { get; set; }
        public string MapVariant_ResourceId { get; set; }
        public Nullable<int> MapVariant_OwnerType { get; set; }
        public string MapVariant_Owner { get; set; }
        public string GameBaseVariantID { get; set; }
        public string GameVariant_ResourceID { get; set; }
        public Nullable<int> GameVariant_ResourceType { get; set; }
        public Nullable<int> GameVariant_OwnerType { get; set; }
        public string GameVariant_Owner { get; set; }
        public Nullable<System.DateTime> MatchCompleteDate { get; set; }
        public string MatchDuration { get; set; }
        public byte[] IsTeamGame { get; set; }
        public string SeasonID { get; set; }
        public string Team1_Company_1 { get; set; }
        public string Team1_Company_2 { get; set; }
        public string Team2_Company1 { get; set; }
        public string Team2_Company2 { get; set; }
    }
}
