//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartanClash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_spartans
    {
        public string gamertag { get; set; }
        public string company { get; set; }
        public string rank { get; set; }
        public Nullable<System.DateTime> date_updated { get; set; }
    }
}
